apiVersion: v1
kind: pod
metadata:
  name: my-production-label-pod
  labels:
    app: my-app
    environment: production
spec:
  containers:
  - name: nginx
    image: nginx
    
    

apiVersion: v1
kind: pod
metadata:
  name: my-annotation-pod
  annotations:
    owner: rmspavan@outlook.com
    git-commit: bdabc066
spec:
  containers:
  - name: nginx
    image: nginx  