my-secret.yml

---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  myKey: myPassword
  
  
  
my-secret-pod.yml

---
apiVersion: v1
kind: pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c' , "echo Hello, Kubernetes! && sleep 3600"]
    env:
    - name: MY_PASSWORD
      valumeFrom:
        secretKeyRef:
          name: my-secret
          key: myKey